version: '3'

services:
  reverse-proxy:
    image: joshualiangxy/reverse-proxy
    build:
      context: .
    container_name: reverse-proxy
    depends_on:
      - hello-world
      - goodbye-world
    ports:
      - 8080:80
    restart: on-failure

  hello-world:
    image: joshualiangxy/hello-world
    container_name: hello-world
    hostname: hello-world-service
    build:
      context: ./hello-world
    ports:
      - 8081:8080
    restart: on-failure

  goodbye-world:
    image: joshualiangxy/goodbye-world
    container_name: goodbye-world
    hostname: goodbye-world-service
    build:
      context: ./goodbye-world
    ports:
      - 8082:8080
    restart: on-failure
